apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-pyro-dev-devops-role
  namespace: pyro-dev
rules:
  - apiGroups: ["apps"]
    resources: ["deployments","pods"]
    verbs: ["list", "watch", "update", "patch", "get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list","update","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-pyro-dev-devops-rolebinding
  namespace: pyro-dev
subjects:
  - kind: ServiceAccount
    name: sa-pyro-dev-devops
    namespace: pyro-dev
roleRef:
  kind: Role
  name: sa-pyro-dev-devops-role
  apiGroup: rbac.authorization.k8s.io
