apiVersion: v1
kind: Secret
metadata:
  name: sa-pyro-dev-devops-token
  namespace: pyro-dev
  annotations:
    kubernetes.io/service-account.name: sa-pyro-dev-devops
type: kubernetes.io/service-account-token

